#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    markie-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^markie\.ddev\.site$`)
      
      service: "markie-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "markie-redirectHttps"
    markie-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^markie\.ddev\.site$`)
      
      service: "markie-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "markie-redirectHttps"
    markie-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^markie\.ddev\.site$`)
      
      service: "markie-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "markie-redirectHttps"
    
    
    
    markie-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^markie\.ddev\.site$`)
      
      service: "markie-web-80"
      ruleSyntax: v3
      
      tls: true
      
    markie-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^markie\.ddev\.site$`)
      
      service: "markie-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    markie-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^markie\.ddev\.site$`)
      
      service: "markie-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    markie-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    markie-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-markie-web:80
        
    markie-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-markie-web:8025
        
    
    
    markie-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-markie-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/markie.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/markie.key